name: Build Image

on:
  repository_dispatch:
  push:
  # schedule: 
  #   - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install --no-install-recommends build-essential devscripts debhelper cmake git libarchive-dev libcurl4-openssl-dev qtbase5-dev qtbase5-dev-tools qtdeclarative5-dev libqt5svg5-dev qttools5-dev libssl-dev qml-module-qtquick2 qml-module-qtquick-controls2 qml-module-qtquick-layouts qml-module-qtquick-templates2 qml-module-qtquick-window2 qml-module-qtgraphicaleffects

    - name: Checkout rpi-imager
      uses: actions/checkout@v2

    - name: Build
      run: |
        cd src
        mkdir build
        cd build
        cmake ..
        make
        docker run -e EXTRA_BINARIES="" --cap-add SYS_ADMIN --device /dev/fuse -v `pwd`/appdir:/app/usr:Z --rm -ti mhitza/linuxdeployqt:5.15.2

    # artifact upload will take care of zipping for us
    - uses: actions/upload-artifact@v1
      with:
        name: pi-imager-appmage
        path: ${{ github.workspace }}/src/build/deploy
